## Sample docker-compose file to run jellenberger/all-purpose-fastai

version: '3'

services:
  jupyter:
    image: jellenberger/fastai-base
    shm_size: '2gb'  # see https://github.com/pytorch/pytorch/issues/2244; increase if necessary
    volumes:
      - ./:/home/appuser/notebooks # working and notebook directory
      - ./data:/home/appuser/data # data directory
    ports:
      - 8888:8888
    container_name: building-recognition
